### ISSUE TITLE
Supported Actions

### ISSUE THREAD

**Issue by outrunthewolf** [thephpleague/omnipay#324]
Is there a method for listing the supported actions on a gateway?

**Comment by delatbabel** [comment]
No, not as such. However most of the methods have a corresponding supports...() method.  Such as supportsAuthorize() to determine if there is an authorize() method (and returns a boolean). So for each given method the same thing can be achieved.

**Comment by outrunthewolf** [comment]
Well would something like an array of supported actions for each gateway be helpful? 

This thread was more an interest into whether its something that people would find helpful rather than a feature request.

If it was deemed helpful we would have considered looking into it as a p/r

**Comment by delatbabel** [comment]
What I would probably find most useful is a method to return a "details" object for a gateway.

That would include the list of methods supported, a list of initialization parameters required, and a flag to indicate the gateway type (redirect, direct card, either/both, manual, etc).

At this stage that's probably an omnipay 3.0 change but if you want to prep a PR anyway then I will take a look at it. We have to touch each gateway for 3.0 because of the move away from Guzzle 3 so that would be an ideal time to incorporate other cross-gateway changes.

**Comment by outrunthewolf** [comment]
Whats the timeline for 3.0?

**Comment by delatbabel** [comment]
I'm not sure at this stage -- probably check with the mailing list or check the 3.0 issues hereabouts.
