### ISSUE TITLE
Recurring billing

### ISSUE THREAD

**Issue by mario** [thephpleague/omnipay#33]
Hey guys,
recurring billing is quite important, how come you are not interested in supporting that?

**Comment by superasn** [comment]
@kayladnls on the main page it says:

>  Feel free to get in touch if you really think this should be a core feature and worth the effort.

I sincerely feel that this should be supported where possible, like 2Checkout, Paypal, etc. 

Almost all *SaaS* companies I know off require recurring billing. 

I was so excited to see this library and I'm sure recurring billing support will only make it 10x useful.

I propose that there should be a way to query the gateway like:

     if ( $gateway->supportsRecurringBilling() ) {
          ...

If you guys are considering it, I'd be more than happy to add code to Paypal and 2Checkout to support recurring billing (as I've implemented them quite a lot for many of my sites). 

It would be great if we can decide the API for supporting recurring billing first.

Your thoughts?

**Comment by adrianmacneil** [comment]
Since I wrote the original readme figure I should add a comment.

The reason we didn't originally support recurring billing isn't that it's not useful, but more because it is hard to abstract the differences between many gateways. I've seen different recurring billing APIs treat things like plans, timeframes, subscriptions, customers, very differently. I think it would be hard to come up with a consistent cross-gateway API for this (especially compared to single credit card charges, which are fairly straightforward).

Of course, it could still be added as a non-standard option in specific gateways (e.g. paypal). That might even be a better place to start, and after implementing a few gateways if we can see some common trends emerge, then that could be added as a common interface.

**Comment by superasn** [comment]
@adrianmacneil that is probably a good idea.. One of my site already have an abstraction layer over PP, 2CO and CCNow (including handling the IPN) and it seems to work just fine.. 

AFAIK there were a minor issues like 2CO not returning a unique IDs for each transaction within subscription but that ways many years ago.. maybe a fork would be a good way to start?

**Comment by nickwuk** [comment]
+1 for subscriptions/recurring billing for Stripe and Paypal.
