### ISSUE TITLE
Replace Graham (Kayla) with me in maintainers for some repos

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/omnipay#382]
Hi,

Are there any objections to me replacing "Kayla Daniels" (now Graham Daniels) as the maintainer in the README file with myself for some of the packages that I have been maintaining recently?  I understand that Graham is pulling back from Omnipay development in any case.

Specifically:

* Stripe
* Pin
* PayPal
* eWay (AU)
* Manual
* Payment Express (NZ)

**Comment by barryvdh** [comment]
As discussed with Graham, we agreed I would take over general maintenance for Omnipay. But I will be focussing mainly on v3 / omnipay common.

I think it would be a good idea to define maintainers for the separate gateways, because it would be pretty much impossible to have knowledge of all the gateways. In my case, I mainly use the off-site gateways (iDeal), as that is most popular in the Netherlands.

So :+1: in maintaining those.

@judgej What do you think, do you have any 'special interest' gateways?

In the process to v3, I would like to appoint one person for a gateway, to take care of it, who actually uses it. So if not one of us, a contributer who has shown effort. And if there is no interest, I suggest we don't convert to v3 until a need actually arises..

**Comment by delatbabel** [comment]
Sounds like a good plan. Likewise I mostly use the gateways that are common in the AU/NZ/SE Asia region so the ones that I have picked are mostly those I have contributed to, actively use, or have clients that actively use.

Oddly enough I already maintain one Netherlands based gateway, MultiCards, but that does not use iDeal.

**Comment by judgej** [comment]
Hi, sounds great. My interest focuses on Sage Pay, Authorize.Net and PAYONE (creating a new driver for that monster with 300 pages documentation to wade through). Also Helcim, though we haven't used that for a while, and it has not had much interest so far. I'd be happy to be the maintainer for those. The others I know very little about. However, they do seem like learning a new language - hard for the first few, but get easier the more you do.

**Comment by judgej** [comment]
I may also get involved in NovelNet this coming month, so that may be another one.

**Comment by barryvdh** [comment]
Updated in https://github.com/thephpleague/omnipay/commit/e04d1552ca79546ae6d002724c312c02e4f23301

If there are any other takers to maintain anything that is now Omnipay, feel free to PR!

/cc @greydnls to inform him of the change.

**Comment by delatbabel** [comment]
I'll pick up "Dummy" because it's a trivial change from Manual.  GoCardless looks like it needs an update so I may as well do that one too. Similarly if I'm going to maintain PayPal I may as well pick up PayFlow.

**Comment by delatbabel** [comment]
#384
