### ISSUE TITLE
Handling subscriptions

### ISSUE THREAD

**Issue by aimeoscom** [thephpleague/omnipay#404]
Is there an officially supported API for handling subscriptions in Omnipay?

Some drivers like PayPal and Stripe implement the methods createSubscription/cancelSubscription but they are not mentioned in any Omnipay docs. Only the createCard/updateCard/deleteCard methods are documented but they are only for storing credit card data.

What are the plans in Omnipay? Will createSubscription/cancelSubscription be officially supported if payment gateways support that feature?

**Comment by judgej** [comment]
So far as I know, there isn't any convention decided for how subscriptions would work. IMO it is probably time to start thinking about it though, because subscriptions are so much more prevalent than when OmniPay was first created - many gateways support a subscription service.

I would assume this is something to be formalised more for OmniPay v3.0 than for V2.x, as V3 is a cleaner slate to work from. So what gateways have already implemented to support subscriptions in V2 is unlikely to change.

That's just my assumption though, but am not aware of any plans contrary to that. The first step, I guess, is to define the problem. What features do subscriptions share? Do they share enough to make normalising the API even practical? TBH, I really don't know the answer to that.

**Comment by judgej** [comment]
On the "defining the problem" front, it seems that there are many subscription services that don't offer payment gateways at all - they just wrap around third-party payment gateways and presumably just hold card tokens that they use at regular intervals. Would we want to support those too?

Some are aimed more at B2B subscriptions and some at B2C subscriptions. The difference (apart from pricing) is in how many additional features they have for integrating with accounting systems and automating invoice generation, and managing "accounts" (which may be authorised for multiple users) rather than just handling payment against a credit/debit card (or bank account, which is a payment method that OmniPay also could do with supporting at some point) etc.

**Comment by aimeoscom** [comment]
What all payment gateways supporting subscriptions seem to have in common is that you can create subscriptions and cancel them. Some are supporting more like suspending and resuming subscriptions. For us create/cancel would be enough in the first run and we would need a hint if the driver supporting these methods by e.g. supportsCreateSubscription/supportsCancelSubscription.

Nobody seems to know when Omnipay v3 will be released and it might even take some more month. In the meantime, we would use v2 and add create a PR adding the required supports* methods if that is OK for you.

**Comment by delatbabel** [comment]
Yes, you can add some supports* methods.

To be honest, however, a library like Omnipay isn't ever going to be able to handle subscriptions in a common way. That's because (depending on the gateway) you're going to need to do things like make regular calls to the gateway checking subscription statuses, manually triggering subscription events, etc.  I have worked on a couple of in-house stand-alone applications that do that, and am working on a new one at the moment which should get open sourced at some point, but this really needs to be done in an application that can have things like its own database and scheduled tasks, not in a library that is just a facade for a set of downstream gateways.

**Comment by aimeoscom** [comment]
Yes, Omnipay is only unifying the PHP interface to handle requests/responses for different payment gateways. It's not a shop system that creates recurring orders or manages them itself. That's what Aimeos is for :-)

**Comment by delatbabel** [comment]
OK I'd never heard of Aimeos but it's as good a forum to mention it as any I guess.  :stuck_out_tongue_closed_eyes: 

One of the issues is that even if you implement a createSubscription() method in any given gateway for omnipay, the parameters for each gateway are going to vary so widely that from a gateway-independence point of view it's relatively worthless.  Most gateways have a similar process and set of parameters for a purchase() call -- you pass in a card detail or a card reference, an amount, a currency, a description, and it happens.  If you look at some of the gateways that have createSubscription() calls the entire process varies a lot between gateways.  Some will require you create a billing plan and then join a customer to that, some require you to make an initial purchase and then call a recurring purchase method on the transaction reference of that purchase, some will require you to create a customer object and then add a subscription, some will do other weird and strange things.  Some don't actually have subscriptions at all but you can repeatedly call purchase() with either a card token or a previous transaction reference to simulate it, from your own daily or monthly cron job.  This is why it's really a use case for an intermediate application or an application plugin (with its own database tables and cron scripts) rather than a library.

Anyway, I think we've exhausted discussion on this so I'll close it.  You can add a PR for supports*() methods (although ideally that PR should go to omnipay v3) and implement those methods in the gateway of your choosing, but Omnipay isn't going to start supporting all possible subscription types in a gateway independent way any more than it's going to suddenly sprout wings and fly.

**Comment by aimeos** [comment]
If you don't know Aimeos yet, you should have a look at it ;-)
Especially the Laravel package is very successful: https://aimeos.org/
