### ISSUE TITLE
Support for recurring payments

### ISSUE THREAD

**Issue by simplenotezy** [thephpleague/omnipay#418]
This library should really support recurring payments, e.g. For Stripe, Braintree, PayPal, QuickPay v10, etc.

**Comment by delatbabel** [comment]
No, because support for recurring payments is beyond the scope of a library.  It requires:

* Recording of customers, subscriptions, payment plans, etc.
* Regular callbacks to gateways to determine whether planned payments are successful or not, or handling callbacks from gateways which notify the application as to the success / failure of a planned payment (depends on the gateway as to which or both must be implemented).
* Handling of different time periods, e.g. some gateways will support a payment every 30 days but some only do monthly which is slightly different.

**Comment by simplenotezy** [comment]
What I meant by recurring billing is most likely what you are calling tokenized payments: https://github.com/thephpleague/omnipay#token-billing

Is it supported for all gateways?

**Comment by judgej** [comment]
Recurring billing and tokenised payments are two very different things, though there is some overlap in some gateways.

Some gateways allow you to set up regular automated billing, and the gateway handles all the payments with no further input from the merchant site. This usually needs additional API functionality to manage customers, timings, notifications of payments etc.

Tokenised payments allow the merchant site to take a payment without the need for the user to enter credit card details again. In this case, any automated/regular payments becomes the responsibility for the merchant site to process when a payment is required. This one is much better supported by OmniPay gateways already.

**Comment by macagoraga** [comment]
seem that omnipay-braintree have support for subscription.
is this now in omnipay all gateways that support it?
