### ISSUE TITLE
Symfony 4 compability

### ISSUE THREAD

**Issue by pinguinjkeke** [thephpleague/omnipay#483]
The package isn't compatible with Symfony 4 and Laravel 5.6 because it switched to symfony 4 components

**Comment by RobvH** [comment]
The underlying cause is the use of Guzzle 3, which is described in the readme. It is not possible for composer to come up with a package set that satisfies that and symfony/http-kernel 4.x

There doesn't seem to be any momentum behind Omnipay 3.x. Perhaps its goals are too lofty? It's not very difficult to do the initial 3.x release as *just* GuzzleHttp support. Then 4.x as other things.

**Comment by brud** [comment]
Is it real to just create intermediate branch without any new features, but with GuzzleHttp support?

**Comment by pinguinjkeke** [comment]
@brud just read release notes for 3.x. It's very easy to upgrade your package to 3.x. You can see latest commits on my omnipay-paymentgateru repository.

**Comment by pinguinjkeke** [comment]
@DevelopByte yes

**Comment by brud** [comment]
@pinguinjkeke thanks, will see

**Comment by delatbabel** [comment]
This is a 3.0 issue, see the roadmap and FAQ
